version: '3'

services:
        db:
                restart: always
                volumes:
                        - ./manage/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
                ports:
                        - 5432:5432
                networks:
                        - internet
        web:
                ports: 
                        - 1234:1234
                links:
                        - db
                        - runner
                depends_on:
                        - db
                        - runner
                networks:
                        - internet
                        - no-internet
        runner:
                ports:
                        - 1337:1337
                networks:
                        - no-internet
        manage:
                links:
                        - web
                        - db
                networks:
                        - internet
                stdin_open: true
                tty: true

networks:
        no-internet:
                driver: bridge
                internal: true
        internet:
                driver: bridge
