version: '3'

services:
        db:
                image: postgres:latest
        web:
                build: ./web
        runner:
                build:
                        context: runner
                        args:
                                IMAGE: python:latest
        manage:
                build:
                        context: manage
                        args:
                          IMAGE: ubuntu:latest
