version: '3'

services:
  db:
    build: ./db
    ports:
      - ${POSTGRES_EXT_PORT}:5432
    restart: always
    networks:
      - internet
    env_file: .env
    volumes:
      - postgresVolume:/var/lib/postgresql/data
      - ./logs:/logs

  redis:
    build:
      context: ./redis
      args:
        REDIS_TASK_LIST: ${REDIS_TASK_LIST}
        REDIS_RESULT_LIST: ${REDIS_RESULT_LIST}
        REDIS_RUNNER_USER: ${REDIS_RUNNER_USER}
        REDIS_RUNNER_PASSWORD: ${REDIS_RUNNER_PASSWORD}
    ports: 
      - ${REDIS_EXT_PORT}:${REDIS_PORT}
    restart: always
    networks:
      - internet
      - no-internet

  web:
    build: ./web
    ports: 
      - ${WEB_PORT}:${WEB_PORT}
    links:
      - db
      - redis
      - runner
    depends_on:
      - db
      - redis
    networks:
      - internet
    env_file: .env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  runner:
    restart: always
    links:
      - redis
    depends_on:
      - redis
    networks:
      - no-internet
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TASK_LIST=${REDIS_TASK_LIST}
      - REDIS_RESULT_LIST=${REDIS_RESULT_LIST}
      - REDIS_RUNNER_USER=${REDIS_RUNNER_USER}
      - REDIS_RUNNER_PASSWORD=${REDIS_RUNNER_PASSWORD}

  manage:
    build: ./manage
    links:
      - web
      - db
    networks:
      - internet
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - tests:/home/docker/app/tests

volumes:
  tests:
  postgresVolume:

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
