version: '3'

services:
  db:
    ports:
      - ${POSTGRES_EXT_PORT}:5432
    restart: always
    volumes:
      - ./manage/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - internet
    env_file: .env

  redis:
    image: redis:alpine
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SOLUTIONS_LIST=solutions
      - REDIS_TESTS_LIST=tests
    restart: always
    networks:
      - internet
      - no-internet

  web:
    ports: 
      - ${WEB_PORT}:${WEB_PORT}
    links:
      - db
      - runner
    depends_on:
      - db
      - redis
      - runner
    networks:
      - internet
      - no-internet
    environment:
      - RUNNER_HOST=runner
    env_file: .env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  runner:
    ports:
      - ${RUNNER_PORT}:${RUNNER_PORT}
    depends_on:
      - redis
    networks:
      - no-internet
    env_file: .env

  manage:
    build: ./manage
    links:
      - web
      - db
    networks:
      - internet
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - tests:/home/docker/app/tests

volumes:
  tests:

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
